spring:
  profiles:
    active:
      - dev
---
server:
  port: 8888
spring:
  profiles: dev
  application:
    name: microservicecloud-config
eureka:
  client:
    service-url:
      defaultZone:  http://eureka-dev:8083/eureka/
---
server:
  port: 9999
spring:
  profiles: test
  application:
    name: microservicecloud-config
eureka:
  client:
    service-url:
      defaultZone:  http://eureka-test:8083/eureka/





